### ISSUE TITLE
Check that Properties only return certain types

### ISSUE THREAD

**Issue by jezzsantos** [TNG/ArchUnitNET#108]
Is there a way to assert that the public getter/setter properties of all types in a namespace, only return values of a set of given types (eg. `string`)?

for example: this class should fail on PropertyB.
```
public class MyClass
{
    public string PropertyA { get; set; }
    public long PropertyB { get; set; }
}
```
Can you give an example of how?

**Comment by jezzsantos** [comment]
I've tried this approach, but its seems like when it executes, the values for `GetPropertyMembers()` is empty for any of my declared types.
 
So, I must be doing something wrong:

```
var violation = ArchRuleDefinition.Types(true).That()
                .ResideInNamespace("MyNamespace", true)
                .Should().OnlyHavePropertiesOfType(new Type[]{typeof(string)});

            violation.Check(this.Setup.Architecture);
```
where: `OnlyHavePropertiesOfType()` is defined like this:
```
public static TRuleTypeShouldConjunction OnlyHavePropertiesOfType<TRuleTypeShouldConjunction, TRuleType>(
            this TypesShould<TRuleTypeShouldConjunction, TRuleType> rule)
            where TRuleTypeShouldConjunction : SyntaxElement<TRuleType>
            where TRuleType : IType
        {
            return rule.FollowCustomCondition(ruleType =>
                {
                    return ruleType.GetPropertyMembers()
                        .All(member =>
                            member.GetterVisibility == Visibility.Public
                            && member.SetterVisibility == Visibility.Public
                            && member.Getter.ReturnType.FullName == "System.String");
                },
                $"only have public getter/setter properties that are 'string'",
                $"had a property with a return type other then 'string'");
        }
```
When this rule executes for any type found, the call to `GetPropertyMembers()` returns an empty collection!

**Comment by fgather** [comment]
@brandhuf , could you look into this?

**Comment by brandhuf** [comment]
Yes, I will look into it.

**Comment by brandhuf** [comment]
I implemented exaclty like you did and it works fine for me. GetPropertyMembers() also returns the correct properties, so I'm not sure what the problem is in your case.

**Comment by jezzsantos** [comment]
Hey @brandhuf, 

I am perplexed. I created a small test project like you did to repro this and cannot repro the problem.
In other words, the types and their properties are returned as advertised.

However, is a far larger codebase (~100 assemblies), the exact same code `ruleType.GetPropertyMembers()` returns only empty collections.

I wonder if there are issues with how we are constructing our `Architecture`.
At the moment, we are doing this:
```
this.Architecture = new ArchLoader()
                .LoadAssemblyIncludingDependencies(typeof(Startup).Assembly)
                .Build();
```
where `Startup` is a class in an ASP.NET project, that implicitly references all the other ~100 or so assemblies, one of which contains the 50 or so types in the specific namespace we are after.

Could there be something wrong in our approach here?

**Comment by brandhuf** [comment]
Hey @jezzsantos ,

I think that the problem lies in the implicit referencing to the assembly with the problematic types. When an assembly is loaded by reference, the AssemblyReference needs to be resolved to an AssemblyDefinition, so that we get access to all information about the types in the assembly. If the AssemblyReference can't be resolved we can still read out some information such as the full name of all referenced types, but not the getter and setter methods of properties.

Maybe in your case the AssemblyResolver fails to resolve the problematic assembly and therefore the getters and setters can't be loaded. You could try to debug this, by setting a stop in the LoadModule() method of the ArchLoader to find out which assemblies can't be resolved.

**Comment by jezzsantos** [comment]
Thanks heaps. I will try that
