### ISSUE TITLE
Slice names have only the dynamic part

### ISSUE THREAD

**Issue by kirchsth** [TNG/ArchUnitNET#113]
I want to create a plantuml diagram based on found errors, eg.
```csharp
            IArchRule noCycles = SliceRuleDefinition.Slices().Matching("ArchUnitNET.(*)").Should().BeFreeOfCycles();
            noCycles.Check(Architecture);
```

but the found slices are all without the "ArchUnitNet." prefix (e.g. "Fluent", but I would expect "ArchUnitNET.Fluent").
Is it possible to add a "full name" property to the slices with the fix parts too?

Thank you and best regards
Helmut

PS.: Atm I use C4-PlantUML but maybe I can extend add a better namesspaces/classes diagram too

![simple](http://www.plantuml.com/plantuml/png/lPJVRzCm4CVV_LSS4QADL8g2AlP2qQQqmAJzGDiGZvFht18pnuvi1uWG_pjnqbXPLOcOXprPET_typsVVJarbcfRbuAyu9A9EaDudwxUfAlxL9MLaYZjicgtFn0o0_F8PKKrBK5mYRQf42eb6lT1o5cMRGMMhU2EvdD9IpGLPRY0bxiyLKBfTIHuNjXSqoPoKQKprDqEh27Q2SeUNVn1ITldTw7u0Cm4DMOC_LbmYw706nGTh672LMZnbztZbAOoxtZkM4-3CI6tZR5OpZUgf5mkO5WZ9x0qDsj_y1X-4u0Px1NHcMR5LydjrVPksSkMBiGjCbjhvpWbnVjqVOZ_vN2z-zvglsZrWxlUK5OuIa3ceT_Oy0XbWnNA32NZQ9QNQ0kLfLG87suMy3-g8uNyyNVnKTGexGA6DV0kUjdo_6a3aXOoDUsmj6Tp6ZNXGj4sQG736jY4NhRl_IMMEzJdqbWg6RQWWDHZ9TwWy0FZBobremS9l8QtmAWGnWk7eJILvXRNqIik7tXhtaJn6EMFEa8bWQYXcW4vGgsITu6mePuZiEJa9016Pk1u4tu7KzzDxnrxyBJn3-UF389dFF2TUSlRpzVVxY-sdxPNctbCJbjQNOg_ )

![detailed](http://www.plantuml.com/plantuml/png/lPJFRjGm4CRlVeeXGj188IXeHIyiQfLTe5B_85h4iV8wqyJKiIFR0IB4knF7krQpMgar1qvMnlFzll7OanDZgRPzAyWpBfdeAuHtvU9rkRWjLTifYTBctRZzdf2NOEwvxAYcBGWkqGuTGgV4u3u8EQsgjS1s5DpG-aZI5ar76MRmV5ENIYYzJ0Il6rjhEYGkgdI5Ujg19IGRGTczYzyfQNt-54htm4nGOnv2VpRSOYpm2ue9DZ3XAhJuosvnIbDPJpnth7am9UHwC1RRevLgAPSPxDR42IojpJ8SF8NV102sWkHKi-QhvFPoVPDxLUv2t2AplNQ6Jqa9DbCRqaSChZRVH-bdhNvmrndA6WU9oDotU-1t0BB23cM5ad4q-GNQHbKb5IA4Xmp-HNMWZZ_X8Zw87gNDmA-n5-5L-Tdy-CN8U6BQVcN_nsZUWdD5nwGC_1hR0g_QDlu2smtgCsaibGn7JaJgeGh7CGkZ4cweT4C71Ro2Dy2e42O8T-DeEiqjBfCNNDxnqNn8qXdA5p935P6eNJKUEKCjYhUHC5_FGLXnV1m18-1mZ_q88bwDjquzDsBm8_617p_TaOyiE5v_klfsUxx-kBvS7QNaPAJrhVWB)

With correct Namespace it could look like
![correct namespace](http://www.plantuml.com/plantuml/png/hPHVRzCm5CNV_Iak4O96Aa515NkXQ5DQODB-e6s8nybrxX8p_udi6o12V7Vah4JjiDHPuZ4dzk_SUspVOq_SKQyLUoQDK7sDyAvQlAuMjvNLdJLegEXwhTupzXBylJGTTro3aWPfw10wguRmmTX9NQyLQZHqmvkPuHfznmNEuVccgQooRfafsRJKE3vaGRMkHZV-WILa6yN5VT3lhA67zQEKFm8BnRtVXVve9M4gy0hL21k42XKI_gGjpZfkcf4NsjeNSyQk1q-ePoTEj5-Cf8lrJR6ocaipXvYM1H3nnY-dG7BunG1W2yh-tLK4IH8Awbqe97lyFJ77BF83jClDDnJqsTdlCiJ3HJj28dAClGEFi5VOeQdH28c-E4TgRLrnfIPvcCF19H7Jtz6SFwWU3SqXfYNaFEqgJlSpA4F_CIsUz_-cnfi-ixn6DuU8bjBqj6jx1EUeD-XEZITkn7ZmSJrQvXMgs0E87qmLdXYKy0hUWE1A-Gduz_7vpad2PVP2cZjf90rPVjXYQcZFeaorY5GSiTsrM9Hl4qqYDHyoAO-E4amO19idJ9AdNjS7wtpa9ioKLFp4Jvyh0PDmkIV7wq-NNs_FrX_N5wjPpexHrBrMVm00)

**Comment by fgather** [comment]
Hi,
I like the diagrams very much. Agreed, the FullName property for the Slices is useful and we should implement it. I can try to do that myself, but I'm also open to Pull-requests ;)

Best Regards,
Florian

**Comment by fgather** [comment]
@andredered, was this fixed by one of your latest PRs?

**Comment by andredered** [comment]
@fgather 

Hmm, the last PR with C4 remains, and yes, in principle, it is ready.
The remaining possible moment: adding inscriptions.
I think it should be implemented for some specific cases.

**Comment by fgather** [comment]
@kirchsth  , does the change work for you? Feel free to reopen, if you expected something different.
