### ISSUE TITLE
Package installation fails in .NET Framework 4.6.1, .NET Core environment.

### ISSUE THREAD

**Issue by ujkim** [TNG/ArchUnitNET#13]
Hello, I was interested in ArchUnitNET to improve the quality of my project's architecture.
But, Now I can't installed in .NET Framework 4.6.1, .NET Core development environments.

Of course the .NET Framework 4.6.1 version is not the latest, But My personal project is currently using version 4.6.1.
If you care about supporting this issue, I'm sure more developers will be able to help improve software quality through this library.

I hope you can apply for the issue.
Thank you!

**Comment by fgather** [comment]
Hey @ujkim ,
we have a windows build and a NET 4.8 package now and are trying to create it for older NET versions as well.

**Comment by ujkim** [comment]
@fgather Thank you very much! 
I'm using on .NET Framework 4.6.1. But, When I tried to install it, it failed.

TngTech.ArchUnitNET.NUnit 0.3.2 Install failed. Rollbak
'TngTech.ArchUnitNET.NUnit.0.3.2' Package doesn't exists in 'A' Project.
'TngTech.ArchUnitNET.NUnit.0.3.2' Package doesn't exists in 'A\packages' Folder
'TngTech.ArchUnitNET.NUnit 0.3.2' Package cannot be installed. 

Hmm I have to do other things?

Anyway thanks.

**Comment by fgather** [comment]
Hi @ujkim ,
sorry, I somehow missed that Github notification. I think one of our dependencies back then did only supported 4.8 upwards. We removed that dependency by now. Let's see if we can make it work for 4.6.

**Comment by fgather** [comment]
Hey @ujkim,

I just released version 0.3.5, which should work for .NET Framework <= 4.5. 

Best Regards,
Florian
