### ISSUE TITLE
ResideInAssembly should have an implementation with Domain.Assembly

### ISSUE THREAD

**Issue by DialLuesebrink** [TNG/ArchUnitNET#131]
At the moment there are two ResideInAssembly methods
One that takes a string and one that takes a Reflection.Assembly it would be nice if there also was a method that uses the Domain.Assembly type.

**Comment by fgather** [comment]
As part of the fix in https://github.com/TNG/ArchUnitNET/issues/126 we can improve that behavior, thanks for the input!

**Comment by fgather** [comment]
@DialLuesebrink this was just released with 0.10.1
