### ISSUE TITLE
It looks like typo in TypeExtensions.CallsMethod(...)

### ISSUE THREAD

**Issue by Denis535** [TNG/ArchUnitNET#14]
[Is it okey or not?](https://github.com/TNG/ArchUnitNET/blob/master/ArchUnitNET/Fluent/Extensions/TypeExtensions.cs#L24)

        public static bool CallsMethod(this IHasDependencies type, MethodMember method)
        {
            return type.GetCalledMethods().Contains(type);
        }

**Comment by brandhuf** [comment]
Yes, you're correct, it is a typo. Thanks for pointing it out.
