### ISSUE TITLE
Do you have coverage to .net 6??

### ISSUE THREAD

**Issue by awilliansd** [TNG/ArchUnitNET#160]
I'm trying to use your lib in .net 6, but I changed the new model namespace and your lib didn't find. Do you have some solution for this?

![image](https://user-images.githubusercontent.com/4139802/167019452-72b65d47-ecb1-42c9-b687-6c979631873b.png)

**Comment by awilliansd** [comment]
This test is throwing errors, because the namespace. I just update the .net 6 and failed my test

![image](https://user-images.githubusercontent.com/4139802/171537865-b3e365d3-9fb3-4dc6-82f1-8e93d98aae0a.png)

**Comment by fgather** [comment]
@awilliansd did you ever find out what was the issue here? Without knowing how the Rules I set up, I failed to reproduce the issue unfortunately. Did the namespaces that ArchUnit is seeing change with .NET 6?

**Comment by awilliansd** [comment]
I did this namespaces. Follow the image

![image](https://user-images.githubusercontent.com/4139802/180783310-f07a5633-924f-4c79-af62-5297aababfed.png)

**Comment by alexanderlinne** [comment]
@awilliansd Does this issue still exist for you? If so, could you please provide a link to a GitHub repo with a minimal project that reproduces the issue?

**Comment by awilliansd** [comment]
> @awilliansd Does this issue still exist for you? If so, could you please provide a link to a GitHub repo with a minimal project that reproduces the issue?

It works now
