### ISSUE TITLE
Can we add an overload with assembly filter support to ArchLoader?

### ISSUE THREAD

**Issue by gbtb** [TNG/ArchUnitNET#164]
Hello! First of all, thank you for the library, it has been really helpful :smiley: 

I'd like to suggest adding another overload to ArchLoader class to support custom user-defined filters for loading assemblies.
Basically, what I want to do is to define small set of "entrypoint" assemblies and load their dependencies recursively, but load only assemblies that I own (I can easily choose them by common name prefix we use).
With current overloads I either have to list all required assemblies directly (which is bad because we certainly will add new ones in the future), or use several invocations of LoadDirectory with specific hard-coded paths which is also quite brittle.

I think this overload should look something like this `LoadAssemblies(params System.Reflection.Assembly[] assemblies, bool includingDependencies, bool recursive, Func<ModuleDefinition, bool> predicate)`. If you're ok with this change, I will submit a PR.

**Comment by fgather** [comment]
Hi gbtb,
that sounds like a gread idea, which can help many others. I'd be happy if you consider to prepare a PR!
