### ISSUE TITLE
Better architecture

### ISSUE THREAD

**Issue by Denis535** [TNG/ArchUnitNET#17]
Now your package consists of one project. It is very difficult to understand dependencies in one project.
I suggest to split it on: Core, Internal/Infrastructure and Extensions/Utils. Core is main code. Internal is helpers. Extensions is utils and syntax sugar (Fluent).
Also I think it would be better to join Core and Domain namespaces to Reflection or Entities namespace. Now your Core is not true core. It's just domain loader.

This is just my opinion.

**Comment by fgather** [comment]
Hi, thanks for the feedback, I think you are right!
Especially I'd like to use ArchUnitNET on itself to keep it that way. Would you be open to create a PR for that? 
@Rubbiroid , @brandhuf  can you help here?

**Comment by Rubbiroid** [comment]
@fgather sure, I will take it over after slices are merged
