### ISSUE TITLE
Is this only a beta version?

### ISSUE THREAD

**Issue by reifenrath-dev** [TNG/ArchUnitNET#231]
Sorry, if the title sounds like an insult. It's just that the nuget version starts with a 0. that's usually an indicator for alpha or beta version. Can you pleas clarify, if this is the case here? Thanks 🙏

**Comment by alexanderlinne** [comment]
No offense taken, don't worry.
You are correct in that currently minor version may include breaking changes and we plan to release a couple more versions in this mode.
