### ISSUE TITLE
Next release ETA?

### ISSUE THREAD

**Issue by VincentH-Net** [TNG/ArchUnitNET#248]
Hi @alexanderlinne, I am considering using ArchUnitNET for a new .NET 8 project, and I noticed that you have been working on it recently. Would you know when the next release of ArchUnitNET will be?

Or if no release is coming soon, what are instructions for building a release from the repo?

Thanks!

**Comment by alexanderlinne** [comment]
Hi @VincentH-Net,

me and @mak638 recently joined this project and are currently testing #201. We are planning to release this change as version 0.11 in the coming weeks.
