### ISSUE TITLE
Static classes are verified as abstract classes. is this correct? 

### ISSUE THREAD

**Issue by jnormen** [TNG/ArchUnitNET#258]
I have a test where I check if I have abstract classes if so then I want it to check if the suffix is Base. 
But when I run the tests it complain on my Extensions classes and my Logger (source generated once.) 

Non of them are marked as abstract. What do I miss? a bug? intented? 

```
 [Fact]
    public void Abstract_Classes_Should_Have_Base_Suffix()
    {
        Classes()
            .That()
            .AreAbstract()
            .Should().HaveNameEndingWith("Base")
            .Because("It's a design rule to name the abstract classes with the suffix 'Base'.")
            .Check(Architecture);
    }
```

complain:
```
...
Infrastructure.Loggers.ServiceLogger does have name ServiceLogger
Lindex.Core.WebApi.EndpointsExtension does have name EndpointsExtension
```
example of an logger extension:
```
  public static partial class ServiceLogger
    {
        [LoggerMessage(
        Level = LogLevel.Information,
        EventName = "ServiceStarting",
        Message = "Start service '{ServiceName}'")]
        public static partial void ServiceStarting(this ILogger logger, string serviceName);
```
in this case it's partial. 

```
   public static class EndpointsExtension
    {
        public static IEndpointRouteBuilder UseAllEndpoints(this IEndpointRouteBuilder builder)
        {
```

**Comment by jnormen** [comment]
Think I know why. seams IL treat static and abstract as same :(

**Comment by mak638** [comment]
Hi, unfortunately this is correct - `static` classes are automatically treated as `abstract`. But they are treated as `sealed` as well! Therefore if you want to check only `abstract` classes that are non-`static` you could try the following workaround:

```csharp
[Fact]
public void Abstract_Classes_Should_Have_Base_Suffix()
{
    Classes()
        .That()
        .AreAbstract()
        .And()
        .AreNotSealed()
        .Should().HaveNameEndingWith("Base")
        .Because("It's a design rule to name the abstract classes with the suffix 'Base'.")
        .Check(Architecture);
}
```

Please let me know if this workaround works for you. If so maybe we can further improve our `Class` class :)

**Comment by jnormen** [comment]
Cool that seams to work :) 
Did not know about the sealed thing. Maybe I shall check the IL more often :)
