### ISSUE TITLE
Dependency on external static classes is not recognized

### ISSUE THREAD

**Issue by Rubbiroid** [TNG/ArchUnitNET#27]
Hi! Found an issue:

```csharp
Classes().That().AreNot(allowedClasses)
     .Should().NotDependOnAny(typeof(JsonConvert))
     .Check(Architecture);
```

Throws an exception:

`ArchUnitNET.Domain.Exceptions.TypeDoesNotExistInArchitecture : Type Newtonsoft.Json.JsonConvert does not exist in provided architecture or is no class...`

JsonConvert contains static methods with are used in the code

**Comment by fgather** [comment]
This should be fixed with the current release. Can you test it?

**Comment by fgather** [comment]
I'll close this, since it should be fixed.
