### ISSUE TITLE
Would it be possible to test every await has also ConfigureAwait?

### ISSUE THREAD

**Issue by Khaos66** [TNG/ArchUnitNET#303]
As we know `await Bar()` will capture the current thread. 
So it's best practice to append `.ConfigureAwait(false)` for the state machine to not capture the thread.

I was hoping this library could help me to enforce that rule. But it doesn't look like there is this kind of 'resolution' down to method calls.

**Comment by mak638** [comment]
Hi @Khaos66, I fear there is no out-of-the-box solution via ArchUnitNET, but there might be a much simpler solution to your problem. In this specific case there is a Code Analysis rule already: [CA2007: Do not directly await a Task](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007).

Hope this is helpful to you.

**Comment by Khaos66** [comment]
Yes that does the trick! Thank you very much <3
