### ISSUE TITLE
Building Assemblies failed 

### ISSUE THREAD

**Issue by nrkim** [TNG/ArchUnitNET#51]
Hello, I tried to use ArchUnitNET (v0.4.3,  .NET Framework 4.6.1 )  But When Building assemblies , exception was occured. 
Is Any wrong with this code? or is it a bug? 
Thank you for your help. 

Code : 
```
[TestClass]
    public class DependencyTests
    {
        private static readonly string clientNamespace = typeof(clientClass).Namespace;
        private static readonly string serverNamespace = typeof(serverClass).Namespace;
        private static readonly Architecture _architecture = new ArchLoader().LoadAssemblies(typeof(clientClass).Assembly, typeof(serverClass).Assembly).Build(); //Error

        [TestMethod]
        public void TestMethod1()
        {            
            IArchRule rule = Types().That().ResideInNamespace(clientNamespace).Should()
                    .NotDependOnAny(Types().That().ResideInNamespace(serverNamespace));

            Assert.IsTrue(rule.HasNoViolations(_architecture));
        }
    }

```

Exception : 
Cannot cast type object'ArchUnitNET.Loader.TypeInstance`1[ArchUnitNET.Domain.Class]' to type'ArchUnitNET.Domain.ITypeInstance`1[ArchUnitNET.Domain.Interface]'.

Location: ArchUnitNET.Loader.LoadTasks.AddClassDependencies. <AddInterfaceDependencies> b__7_0 (TypeReference target)
    Location: ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach [T] (IEnumerable`1 source, Action`1 action)
    Location: ArchUnitNET.Loader.LoadTasks.AddClassDependencies.AddInterfaceDependencies()
    Location: ArchUnitNET.Loader.LoadTasks.AddClassDependencies.Execute()
    Location: ArchUnitNET.Loader.LoadTaskRegistry. <ExecuteTasks> b__1_1 (type taskKey)
    Location: ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach [T] (IEnumerable`1 source, Action`1 action)
    Location: ArchUnitNET.Loader.LoadTaskRegistry.ExecuteTasks (List`1 taskOrder)
    Location: ArchUnitNET.Loader.ArchBuilder.UpdateTypeDefinitions()
    Location: ArchUnitNET.Loader.ArchBuilder.Build()
    Location: ArchUnitNET.Loader.ArchLoader.Build()
    Location: DependencyTests.TestMethod1() File

**Comment by brandhuf** [comment]
Hi,

we've tried to replicate the problem, but without success. It seems that a class in your architecture is mistakenly interpreted as an interface during loading. Could you please step in the AddInterfaceDependencies() method where the exception is thrown and give us some information on the type which throws an exception at the attempt to cast it to ITypeInstance<Interface>?

**Comment by nrkim** [comment]
II'm sorry late.
I tried to find exact type of ITypeInstance from exception details message, but it was difficult to find valid information among exception details. I finally found typeInstance after I extracted AddInterfaceDependencies function using reflection, and called function alone.  I'm not sure which information is useful  so, added _typeDefinition  information.  if any other information you need, give me some direction. thank you.

1. Structure of error class 
`
public TypeErrorClass : AbstractClassA, InterfaceB, interfaceC
{
	....
}
`
(may Class which derives combination of abstract class and interfaces  cause a problems ? )

2. _typeDefinition 
`-		_typeDefinition	{xxx}	object {Mono.Cecil.TypeDefinition}
		Attributes	Public | BeforeFieldInit	Mono.Cecil.TypeAttributes
+		BaseType	{xxxxBase}	Mono.Cecil.TypeReference {Mono.Cecil.TypeDefinition}
		ClassSize	-1	int
		ContainsGenericParameter	false	bool
+		CustomAttributes	{Mono.Collections.Generic.Collection<Mono.Cecil.CustomAttribute>}	Mono.Collections.Generic.Collection<Mono.Cecil.CustomAttribute>
		DeclaringType (Mono.Cecil.TypeReference)	null	Mono.Cecil.TypeReference
		DeclaringType	null	Mono.Cecil.TypeDefinition
+		Events	{Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.EventDefinition>}	Mono.Collections.Generic.Collection<Mono.Cecil.EventDefinition> {Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.EventDefinition>}
+		Fields	{Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.FieldDefinition>}	Mono.Collections.Generic.Collection<Mono.Cecil.FieldDefinition> {Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.FieldDefinition>}
		FullName	"xxxxxxxxxxxxxxxx"	string
+		GenericParameters	{Mono.Cecil.GenericParameterCollection}	Mono.Collections.Generic.Collection<Mono.Cecil.GenericParameter> {Mono.Cecil.GenericParameterCollection}
		HasCustomAttributes	false	bool
		HasEvents	false	bool
		HasFields	true	bool
		HasGenericParameters	false	bool
		HasInterfaces	true	bool
		HasLayoutInfo	false	bool
		HasMethods	true	bool
		HasNestedTypes	true	bool
		HasProperties	false	bool
		HasSecurity	false	bool
		HasSecurityDeclarations	false	bool
+		Interfaces	{Mono.Cecil.InterfaceImplementationCollection}	Mono.Collections.Generic.Collection<Mono.Cecil.InterfaceImplementation> {Mono.Cecil.InterfaceImplementationCollection}
		IsAbstract	false	bool
		IsAnsiClass	true	bool
		IsArray	false	bool
		IsAutoClass	false	bool
		IsAutoLayout	true	bool
		IsBeforeFieldInit	true	bool
		IsByReference	false	bool
		IsClass	true	bool
		IsDefinition	true	bool
		IsEnum	false	bool
		IsExplicitLayout	false	bool
		IsFunctionPointer	false	bool
		IsGenericInstance	false	bool
		IsGenericParameter	false	bool
		IsImport	false	bool
		IsInterface	false	bool
		IsNested	false	bool
		IsNestedAssembly	false	bool
		IsNestedFamily	false	bool
		IsNestedFamilyAndAssembly	false	bool
		IsNestedFamilyOrAssembly	false	bool
		IsNestedPrivate	false	bool
		IsNestedPublic	false	bool
		IsNotPublic	false	bool
		IsOptionalModifier	false	bool
		IsPinned	false	bool
		IsPointer	false	bool
		IsPrimitive	false	bool
		IsPublic	true	bool
		IsRequiredModifier	false	bool
		IsRuntimeSpecialName	false	bool
		IsSealed	false	bool
		IsSentinel	false	bool
		IsSequentialLayout	false	bool
		IsSerializable	false	bool
		IsSpecialName	false	bool
		IsUnicodeClass	false	bool
		IsValueType	false	bool
		IsWindowsRuntime	false	bool
		IsWindowsRuntimeProjection	false	bool
+		MetadataToken	{[TypeDef:0x001a]}	Mono.Cecil.MetadataToken
		MetadataType	Class	Mono.Cecil.MetadataType
+		Methods	{Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.MethodDefinition>}	Mono.Collections.Generic.Collection<Mono.Cecil.MethodDefinition> {Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.MethodDefinition>}
+		Module	{xxxx.exe}	Mono.Cecil.ModuleDefinition
		Name	"xxxxxxxxxx"	string
		Namespace	"XXXXXXXXXX"	string
+		NestedTypes	{Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.TypeDefinition>}	Mono.Collections.Generic.Collection<Mono.Cecil.TypeDefinition> {Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.TypeDefinition>}
		PackingSize	-1	short
+		Properties	{Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.PropertyDefinition>}	Mono.Collections.Generic.Collection<Mono.Cecil.PropertyDefinition> {Mono.Cecil.MemberDefinitionCollection<Mono.Cecil.PropertyDefinition>}
+		Scope	{XXXXX.exe}	Mono.Cecil.IMetadataScope {Mono.Cecil.ModuleDefinition}
+		SecurityDeclarations	{Mono.Collections.Generic.Collection<Mono.Cecil.SecurityDeclaration>}	Mono.Collections.Generic.Collection<Mono.Cecil.SecurityDeclaration>
+		generic_parameters	{Mono.Cecil.GenericParameterCollection}	Mono.Collections.Generic.Collection<Mono.Cecil.GenericParameter> {Mono.Cecil.GenericParameterCollection}
+		public	
`

**Comment by fgather** [comment]
Hi @nrkim  , could you test it again with the current release?

**Comment by nrkim** [comment]
@fgather  Type cast error is passed but another error occured when assemblies are built. (latest version v0.5.2)

```
location : private static readonly Architecture _architecture = new ArchLoader().LoadAssemblies(typeof(clientClass).Assembly, typeof(serverClass).Assembly).Build(); //Error

System.NullReferenceException {"Object reference not set to an instance of the object"}
   Location: ArchUnitNET.Domain.Attribute..ctor (Class cls)
   Location: ArchUnitNET.Loader.LoadTasks.AddAttributesAndAttributeDependencies. <CreateAttributesFromCustomAttributes> b__12_0 (CustomAttribute customAttribute)
   Location: System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   Location: System.Collections.Generic.List`1..ctor (IEnumerable`1 collection)
   Location: System.Linq.Enumerable.ToList [TSource] (IEnumerable`1 source)
   Location: ArchUnitNET.Loader.LoadTasks.AddAttributesAndAttributeDependencies.CollectMemberAttributesAndDependencies (IMember methodMember, List`1 memberCustomAttributes, List`1 attributeDependencies)
   Location: ArchUnitNET.Loader.LoadTasks.AddAttributesAndAttributeDependencies.SetUpAttributesForFields (FieldDefinition fieldDefinition)
   Location: ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach [T] (IEnumerable`1 source, Action`1 action)
   Location: ArchUnitNET.Loader.LoadTasks.AddAttributesAndAttributeDependencies.CollectAttributesForMembers()
   Location: ArchUnitNET.Loader.LoadTasks.AddAttributesAndAttributeDependencies.Execute()
   Location: ArchUnitNET.Loader.LoadTaskRegistry. <ExecuteTasks> b__1_1 (type taskKey)
   Location: ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach [T] (IEnumerable`1 source, Action`1 action)
   Location: ArchUnitNET.Loader.LoadTaskRegistry.ExecuteTasks (List`1 taskOrder)
   Location: ArchUnitNET.Loader.ArchBuilder.UpdateTypeDefinitions()
   Location: ArchUnitNET.Loader.ArchBuilder.Build()
   Location: ArchUnitNET.Loader.ArchLoader.Build()
   Location: Test.SI.E.MCS.FDS.DependencyTests.TestMethod1() File D:\TST\Tools\Projects\nrkim\archunit\tests\Test.SI.E.MCS.FDS\DependencyTests.cs: line 26```

**Comment by fgather** [comment]
Hi @nrkim ,
I just released a version containing the fix. It looks like there are problems when a dll which is referenced by youre architecture is missing. We are currently working on a way to test those scenarios better.

**Comment by nrkim** [comment]
now, code is working well. Thank you!!
