### ISSUE TITLE
Custom rules (predicates and conditions)

### ISSUE THREAD

**Issue by Yaevh** [TNG/ArchUnitNET#53]
I cannot seem to find a way to define custom predicates and conditions. Am I missing something, or is this part or ArchUnit not implemented?

**Comment by brandhuf** [comment]
I just created a PR (#55) with this feature

**Comment by fgather** [comment]
I reviewed and merged it. @brandhuf , can you also update the documentation if you have time? Thanks!

**Comment by fgather** [comment]
Will be part of 0.5.0
