### ISSUE TITLE
installing ArchUnitNET.xUnit breaks xUnit

### ISSUE THREAD

**Issue by Yaevh** [TNG/ArchUnitNET#54]
After installing `ArchUnitNET.xUnit` in an existing `xUnit` test project, existing tests fail to compile with error `Error	CS0433	The type 'Assert' exists in both 'ArchUnitNET.xUnit, Version=0.4.3.0, Culture=neutral, PublicKeyToken=null' and 'xunit.assert, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'`.
The reason is that `ArchUnitNET.xUnit` defines a partial class `XUnit.Assert`, but the compiler doesn't support partial classes declared in different assemblies. The solution would be to rename `XUnit.Assert` to `XUnit.ArchRuleAssert`, as it is in `ArchUnitNET.NUnit`.

**Comment by fgather** [comment]
Sounds like a good idea, will do

**Comment by brandhuf** [comment]
Have you tried removing the dependency to xunit and just use ArchUnitNET.xUnit instead? It should work that way

**Comment by Yaevh** [comment]
@brandhuf Either I'm doing something wrong, or your solution doesn't work in .NET 5. And even if it did, it would still feel a bit hackish :/

**Comment by fgather** [comment]
@Yaevh , I agree, I think we should move it @brandhuf

**Comment by brandhuf** [comment]
I moved and renamed the assert class to ArchUnitNET.xUnit.ArchRuleAssert in PR #57

**Comment by fgather** [comment]
@Yaevh , ArchRuleAssert.ArchRule().. sounds a bit too much, right? Do you have a better idea?

**Comment by brandhuf** [comment]
I renamed it to ArchRuleAssert.CheckRule()

**Comment by fgather** [comment]
Release 0.5.0 will be on nuget soon. Since this is a breaking change, there is a small version bump
