### ISSUE TITLE
Create a naming rule for a simple generic class

### ISSUE THREAD

**Issue by Der-Kraken** [TNG/ArchUnitNET#58]
Hello. After playing around for simple naming rules I got to a point I don't know how to write it.

Below you can see a class model of the CQRS-pattern. Simple naming rules I got on my own. But know I want to write a rule which check the prefix of the "Handler"-class.

The rule should be:
Handler naming must match the name of the request (first generic argument) except their own naming suffix (-Handler, and -Response).

``` csharp
public class MyOwnRequest : IRequest<MyOwnResponse>
{
}

public class MyOwnResponse : IResponse
{
}

// The name of this handler must have the prefix 'MyOwn' because the first generic arg (request) has it.
public class MyOwnHandler : IHandler<MyOwnRequest, MyOwnResponse>
{
}
```

**Comment by brandhuf** [comment]
Hi,
you will need to create a custom condition for this rule. One way to implement this would be:

`
var rule = Classes().That().ImplementInterface("IHandler").Should().FollowCustomCondition(cls =>
                    cls.Name.StartsWith(GetPrefix(cls.GetImplementsInterfaceDependencies()
                        .First(dep => dep.Target.FullNameContains("IHandler")).TargetGenericArguments.First().Type)),
                "have correct handler prefix",
                "does not have correct handler prefix");
                
public static string GetPrefix(IType type)
{
    return type.Name.Replace("Request", "").Replace("Response", "");
}
`

**Comment by Der-Kraken** [comment]
Thats a brilliant rule you have wrote. It works fine. Many thanks to you!
