### ISSUE TITLE
Inspecting attributes

### ISSUE THREAD

**Issue by Yaevh** [TNG/ArchUnitNET#60]
Right now, ArchUnitNET allows us to test whether our classes are decorated with certain attributes (via either `Classes().Should().HaveAnyAttributes(typeof(MyAttribute))` or `Class.HasAttribute("MyAttribute")`. However, in most cases it's not only the presence of an attribute that is important, but also its properties (or its value, which is just a special case of a single property).

For example, in my current project I have a requirement that not only all the event classes should be marked with a `EventDefinition` attribute, but also that this attribute should define a name conforming to some domain-specific rules. So basically all the event classes should look like this:

```
public namespace MyModule
{
    [EventDefinition(Name = "MyModule.EmailSentEvent")]
    public class EmailSentEvent : IEvent
    {
        // some event data
    }
}
```

Unfortunately, ArchUnitNET doesn't seem to provide any way to inspect the properties of an attribute. There's neither out-of-the-box method that checks the value of an attrubite, nor the built-in properties and extension methods on `ArchUnitNET.Domain.Attribute` seem to offer any way of inspecting those properties. They seem to be concerned mainly with the *attribute type* itself, while it's an *attribute instance* that is bound to a class and needs to be inspected.

So, how can I inspect the properties of an attribute that a certain class is decorated with? Am I missing something, or there's currently no way to do this in ArchUnitNET?

**Comment by brandhuf** [comment]
Sadly, this feature is not implemented yet, but I will look into it!

**Comment by fgather** [comment]
This has been released today with 0.7.0. @Yaevh , is this solving the issue?

**Comment by Yaevh** [comment]
Somewhat, but not fully.
0.7.0 allows for checking attribute arguments against a predefined set of objects. What it doesn't allow, however, is checking them via a callback that could verify each attribute separately (i.e. when each attribute's arguments depend on the class being decorated).

So basically something like this:
```
var archRule = Classes()
  .That()
    .ImplementInterface(typeof(IAggregateEvent))
  .Should()
    .HaveAttribute<EventNameAttribute>((@class, attr) => attr.ConstructorArguments.Single().EndsWith(@class.Name));
```

**Comment by brandhuf** [comment]
You could write a custom condition like this:

```csharp
Classes().That().ImplementInterface(typeof(INameEvent)).Should().FollowCustomCondition(@class =>
       @class.AttributeInstances.Any(attr =>
            attr.Type.Name == "EventNameAttribute" &&
            attr.AttributeArguments.Any(arg => arg.Value is string val && val.EndsWith(@class.Name)))
    , "have EventNameAttribute with correct parameters"
    , "does not have EventNameAttribute with correct parameters");
```
