### ISSUE TITLE
System.InvalidCastException

### ISSUE THREAD

**Issue by wiewiur25** [TNG/ArchUnitNET#61]
Hello!

I have problem with loading assemblies. This is my code:
` public void LoadAssemblies()
{
    _architecture = new ArchLoader()
           .LoadAssemblies(typeof(Sm.Aspen.Domain.IAssemblyMarker).Assembly,
                 typeof(Sm.Aspen.Messages.IAssemblyMarker).Assembly)
            .Build();
 }` 

and this part of code throwing exception:
`OneTimeSetUp: System.InvalidCastException : Unable to cast object of type 'ArchUnitNET.Loader.TypeInstance`1[ArchUnitNET.Domain.Class]' to type 'ArchUnitNET.Domain.ITypeInstance`1[ArchUnitNET.Domain.Interface]'.`

please let me know if it bug or I do something wrong.

Thank you in advance.
Have a nice day!

**Comment by fgather** [comment]
Hi, 
this looks like a bug to me. Do you have any information on where exactly this happens? Stacktrace? Or can you even write a tests that replicates this issue?

Thanks a lot!

**Comment by wiewiur25** [comment]
Hi,

I have stacktrace:
`System.InvalidCastException: Unable to cast object of type 'ArchUnitNET.Loader.TypeInstance`1[ArchUnitNET.Domain.Class]' to type 'ArchUnitNET.Domain.ITypeInstance`1[ArchUnitNET.Domain.Interface]'.
at ArchUnitNET.Loader.LoadTasks.AddClassDependencies.<AddInterfaceDependencies>b__7_0(TypeReference target)
at ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
at ArchUnitNET.Loader.LoadTasks.AddClassDependencies.Execute()
at ArchUnitNET.Loader.LoadTaskRegistry.<ExecuteTasks>b__1_1(Type taskKey)
at ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
at ArchUnitNET.Loader.ArchBuilder.Build()
at ArchUnitNET.Loader.ArchLoader.Build()`

probably I can't write test to replicate it, because I dont know whats going on.

**Comment by wiewiur25** [comment]
Hello,

any news?

**Comment by brandhuf** [comment]
Hi,

sorry for the late response. This seems like a bug to me, probably the same as Issue #51 . I will try to fix it next week.

**Comment by fgather** [comment]
Hi @wiewiur25 , could you test it again with the current release?

**Comment by wiewiur25** [comment]
sorry for long response, I didn't have time.

now its look ok. Thank you very much!
