### ISSUE TITLE
Feature Request: PlantUML Support

### ISSUE THREAD

**Issue by SeMuell** [TNG/ArchUnitNET#78]
Similar as in original [ArchUnit](https://www.archunit.org/userguide/html/000_Index.html#_plantuml_component_diagrams_as_rules) the PlantUML support is long awaited and would help on improving the relationship between documentation and code.

Before I start some development I would like to start some discussions here, because I saw a fork from @studix who worked on this for some time.

**Comment by studix** [comment]
@SeMuell I‘m almost there with basic plantuml support in my fork. The implementation is considering only the dependencies defined in the plantuml file so far (no other options as the Java version does). Also there is no ignore dependency support.

What‘s open is manual testing with some projects. I try to finish this soon.

**Comment by SeMuell** [comment]
That's great to hear @studix, thanks for the fast response. I think such basic implementation would already help a lot. I may also be able to test the implementation with some projects.

**Comment by fgather** [comment]
@studix , let me know if @brandhuf or I can support you. Feel free to open an early pull-request, so I can give feedback also on an intermediate state. Thanks a lot for you effort!

**Comment by fgather** [comment]
Thank you @studix , I just merged and released the PR. Thanks for improving ArchUnit!
