### ISSUE TITLE
ImplementInterface conjunction should support Type parameter

### ISSUE THREAD

**Issue by fgather** [TNG/ArchUnitNET#9]
Hi @brandhuf ,

HaveAnyAttributes(typeof(DecorateAttribute)) supports Type parameter, however some Conjunctions only support string patterns , like: ImplementInterface(nameof(IDecorator));

Can you extend the conjunctions in that regard?

**Comment by brandhuf** [comment]
pull request #10 added support for more input parameters for some conjunctions, including ImplementInterface(typeof(...))

**Comment by fgather** [comment]
Hi, I merged the PR, thanks a lot!
