### ISSUE TITLE
DocumentationRequest: Documentation for PlantUml support

### ISSUE THREAD

**Issue by studix** [TNG/ArchUnitNET#95]
Support for PlantUml was recently added to ArchUnitNet. There is currently no documentation available for this feature. It would be good to extend [the docs](https://archunitnet.readthedocs.io/en/latest/).

**Comment by studix** [comment]
I could work on this.

**Comment by fgather** [comment]
Hi Marco, 
that sounds great, thanks!

**Comment by ChangeTheCode** [comment]
Looks like this issue can be closed should be resolved with the PR #95

**Comment by studix** [comment]
I cannot find the section I added with #95 in the latest user guide. What is missing?

**Comment by ChangeTheCode** [comment]
@studix  sorry I guess i linked the wrong PR I mean #127. 
[Link to your section](https://github.com/TNG/ArchUnitNET/blob/main/documentation/docs/guide.md#43-plantuml-component-diagrams-as-rules)

**Comment by studix** [comment]
I see it in git but how do we deploy this change to the [latest user guide](https://archunitnet.readthedocs.io/en/latest/guide/) ?

**Comment by fgather** [comment]
Hi @studix ,
I assume it is not there, since it was not released yet. I'm trying to build a release soon, but there are some issues with Travis right now.

**Comment by alexanderlinne** [comment]
The documentation is now up-to-date in the [`latest` documentation](https://archunitnet.readthedocs.io/en/latest/) and will be published to the [`stable` documentation](https://archunitnet.readthedocs.io/en/stable/) documentation with the next release.
