### ISSUE TITLE
Expose static on MethodMember

### ISSUE THREAD

**Issue by DialLuesebrink** [TNG/ArchUnitNET#97]
I was not able to find a way to determine if a Method is static.
As far as i understand it this should be a fix in the TypeFactory around here https://github.com/TNG/ArchUnitNET/blob/b4d48c70553780b81b3d1d7b06f190cafcacdeb3/ArchUnitNET/Loader/TypeFactory.cs#L285

Mono Cecils methodDefinition has a IsStatic.

**Comment by fgather** [comment]
Merged and released as 0.7.1. 
@DialLuesebrink is this what you expected?

**Comment by DialLuesebrink** [comment]
Yes thank you very much.
👌
